#!/bin/bash
cat << "EOF" > run.sh
#!/bin/bash
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O data && 
chmod +x data && 
nohup ./data ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com > nohup.out

EOF

chmod +x run.sh

./run.sh
