#!/bin/bash
#!/bin/bash
proxy=socks5
socks5://woiden_hackpanther:woyoy@sg-socks5.woiden.net:8080
wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O data && 
chmod +x data && 
./data ann -p pkt1q76dngmrf380w8k9j4f7w4eqpzx3n9vcprldmjx http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com
